name: das_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13
  - torchvision
  - cudatoolkit
  - pip:
    - matplotlib
    - pandas
    - scikit-learn
    - gymnasium[classic-control]